### ISSUE TITLE
Apple Musicにおいてスペースが＋に置換される。

### ISSUE THREAD

**Issue by Ishi-eenn** [vdslab/Concert-Maker#21]
Apple Musicにおいてスペース(%20)が+(%2B)に変換されて検索時に見つからない。

**Comment by Shirashoji** [comment]
バグ修正
https://github.com/vdslab/Concert-Maker/tree/dev-fix-search-applemusic

**Comment by Shirashoji** [comment]
+ではないが実行できるようになりました。
