### ISSUE TITLE
タブの部分のスクロール

### ISSUE THREAD

**Issue by Shirashoji** [vdslab/Concert-Maker#9]
タブとその下のコンテンツが丸ごとスクロールされる。
<img width="1512" alt="スクリーンショット 2024-07-10 11 26 14" src="https://github.com/vdslab/Concert-Maker/assets/46389417/e817f75e-fcd8-461f-b1d6-9db954b2366a">

**Comment by Ishi-eenn** [comment]
現状使わなくなったのでクローズします。
